// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLaVWZ4LyP1NyxTYHgMcnHkbMupAyeAA',
    appId: '1:576930394960:web:c4f9232fa6da4c911af255',
    messagingSenderId: '576930394960',
    projectId: 'driverapp-fbf37',
    authDomain: 'driverapp-fbf37.firebaseapp.com',
    storageBucket: 'driverapp-fbf37.firebasestorage.app',
    measurementId: 'G-T0FVRLCXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ38PK8kl0u0nD64JnPqGCy3s4bW1TTSY',
    appId: '1:576930394960:android:f9a72847417623d71af255',
    messagingSenderId: '576930394960',
    projectId: 'driverapp-fbf37',
    storageBucket: 'driverapp-fbf37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvXZ-FDjy665EdM_b0xbx5tHr1iUE0TA',
    appId: '1:576930394960:ios:346afef9c7aa757d1af255',
    messagingSenderId: '576930394960',
    projectId: 'driverapp-fbf37',
    storageBucket: 'driverapp-fbf37.firebasestorage.app',
    iosClientId: '576930394960-eghmb2b4mc8erakb7f7ktd49pisl3o4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimrapj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvXZ-FDjy665EdM_b0xbx5tHr1iUE0TA',
    appId: '1:576930394960:ios:346afef9c7aa757d1af255',
    messagingSenderId: '576930394960',
    projectId: 'driverapp-fbf37',
    storageBucket: 'driverapp-fbf37.firebasestorage.app',
    iosClientId: '576930394960-eghmb2b4mc8erakb7f7ktd49pisl3o4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimrapj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmLaVWZ4LyP1NyxTYHgMcnHkbMupAyeAA',
    appId: '1:576930394960:web:5b78d170019135cb1af255',
    messagingSenderId: '576930394960',
    projectId: 'driverapp-fbf37',
    authDomain: 'driverapp-fbf37.firebaseapp.com',
    storageBucket: 'driverapp-fbf37.firebasestorage.app',
    measurementId: 'G-4EHSWH8PDD',
  );
}
